### ISSUE TITLE
Source files are sometimes read and written with differing charsets

### ISSUE THREAD

**Issue by sirthias** [sbt/sbt-header#105]
sbt-header reads source files with the system's default charset and writes them with UTF-8.
If there is a mismatch between the two sbt-header messes up the files original encoding.

**Comment by britter** [comment]
I wonder whether this is related to #56...

**Comment by sirthias** [comment]
Yes, might well be.
Thanks for looking at this patch, Benedikt.

Do you already have a rough date for the next release planned?

**Comment by britter** [comment]
The only thing I need to finish for 2.0.0 is #90 and #99. I've a working implementation of #90 on my machine but the scripted tests do not work and I can't figure out why. I'll need some time to investigate that. After that's done I can ask @hseeberger to release 2.0.0.

**Comment by sirthias** [comment]
Ok, great!
Thanks for your work here! It really is appreciated!
