### ISSUE TITLE
Suppress newLine after header comment

### ISSUE THREAD

**Issue by mkurz** [sbt/sbt-header#116]
Using
```
headerLicense := Some(HeaderLicense.Custom(
        """|Copyright (c) Awesome Company 2015
           |""".stripMargin
     ))
```
or
```
headerLicense := Some(HeaderLicense.Custom(
        """|Copyright (c) Awesome Company 2015""".stripMargin
     ))
```

both results in:

```
/*
 * Copyright (c) Awesome Company 2015
 */

package mypackage;
```

**How to supress the empty line between the header comment and the package declaration?**

**Comment by hseeberger** [comment]
I think that's not possible.

**Comment by mkurz** [comment]
This was possible in v1.8 but not in v2.0 anymore...

Wouldn't it be possible to *not* add the new line if there will be a body after the header? At least with an setting?

**Comment by hseeberger** [comment]
A `headerEmptyLine` setting of type `Boolean` sounds like a nice idea. Feel free to create a PR.

**Comment by mkurz** [comment]
@hseeberger see #117

Could you cut a new release after merging #117? Thanks!

**Comment by mkurz** [comment]
I am closing this because it's not an issue any more for me. See https://github.com/sbt/sbt-header/pull/117#issuecomment-367388250
Feel free to open a new issue or re-open this one here if you think that should be implemented.
