### ISSUE TITLE
Release plugin for sbt 1.0.0-M6

### ISSUE THREAD

**Issue by jvican** [sbt/sbt-header#119]
Examples:
  
* https://github.com/ktoso/sbt-jmh/pull/117
* https://github.com/lucidsoftware/neo-sbt-scalafmt/pull/11

**Comment by hseeberger** [comment]
Won't before sbt 1.0 reaches RC status.

**Comment by jvican** [comment]
There are already plugins doing so -- see description of issue. The reason I ask for this is because we plan to use sbt 1.0.0-M6 in Zinc and we depend on this plugin.

**Comment by britter** [comment]
I currently don't have time to work on this. @hseeberger how would you feel about making this happen, if somebody prepares a PR for this?

**Comment by jvican** [comment]
Can't this be reopen? RC2 is already out.

**Comment by hseeberger** [comment]
I tried, but too many dependencies which aren't yet on 1.0 :-(

**Comment by SethTisue** [comment]
how about now...?
