### ISSUE TITLE
HeaderCreator leaking file descriptors

### ISSUE THREAD

**Issue by krchniam** [sbt/sbt-header#127]
Hi, 
recently we were having serious troubles using sbt-header plugin on Windows 10 with git. Especially with enabled `AutomateHeaderPlugin`. While running SBT almost every operation with git failed (pull, revert, rebase) with odd errors about unable to unlink old file. You have to turn SBT off, then execute git operation and then turn SBT back on to continue development (which is pretty annoying).

I've located cause to the `HeaderCreator`, line `val fileContent = scala.io.Source.fromInputStream(input)(Codec.UTF8).mkString`. `Source.fromInputStream` is not closing `input`, so file descriptor is open till SBT is closed, thus preventing git and sometimes event IntelliJ IDEA to modify file. Even in case file was not modified by the user, but only check for correct header.

Simply wrapping it and close input stream will do the magic (I'm not sure why `InputStream` is passed down, instead of `Path`):
```
    val fileContent = try {
      scala.io.Source.fromInputStream(input)(Codec.UTF8).mkString
    } finally {
      input.close()
    }
```

**Comment by hseeberger** [comment]
Thanks for reporting and analyzing. PR very welcome.
