### ISSUE TITLE
The 3.0.1 version fails to close files properly

### ISSUE THREAD

**Issue by drewhk** [sbt/sbt-header#129]
This leads to various issues on Windows:
 - chopped files, as Windows caches more aggressively and not-closing means last chunks might be unflushed
 - IntelliJ freaks out continuously as it cannot auto-save files, since the plugin keeps them open. On windows only one process is allowed to write to a file at the same time.

**Comment by drewhk** [comment]
Some variant of this bug seems to exist on 2.0.0 as well, although not sure if it is the same.

**Comment by hseeberger** [comment]
Duplicate of #127?

**Comment by hseeberger** [comment]
@drewhk just released v3.0.2 which should fix this: please give it a try. And of course don't use Windows ;-)

**Comment by drewhk** [comment]
> And of course don't use Windows ;-)

Windows is only relevant here because it exposes the issue much quicker ;)

**Comment by drewhk** [comment]
yes, seems duplicate, but I give the new version a try first.

**Comment by drewhk** [comment]
> just released v3.0.2 which should fix this: please give it a try.

Is it published, or I need to build it locally?

**Comment by britter** [comment]
@drewhk see https://bintray.com/hseeberger/sbt-plugins/sbt-header/3.0.2

**Comment by drewhk** [comment]
Seems to work, I will report back if something is off.
