### ISSUE TITLE
Using sbt-header in scala sbt build

### ISSUE THREAD

**Issue by pierre-borckmans** [sbt/sbt-header#13]
Hi there,
I'm trying to use this nice plugin with a full scala sbt definition (`build.scala`, not `build.sbt`).

In order to be able to define the `headers` map, I had to import the following:
```
import de.heikoseeberger.sbtheader.SbtHeader.autoImport._
import de.heikoseeberger.sbtheader.SbtHeader.HeaderPattern
```

I then define the `headers` map in my project settings:
```
  lazy val core: Project =
    Project(id, file(base))
      .settings(
        // SbtHeader settings
        headers := Map(
          "scala" -> (
            (HeaderPattern.cStyleBlockComment,
              """|/*
                 | * Test header
                 | */
                 |
              """.stripMargin
            )
          )
        )
      )
```

I am then able to create the headers interactively in sbt:
```
$ sbt
> createHeaders
```

However, I cannot get this task to be automatically executed with the `compile` and `test` tasks.

Could you please add an example on how to use your plugin correctly in a `build.scala` build definition?

**Comment by hseeberger** [comment]
First, I recommend upgrading to the just released v1.3.0. The README has been improved, including a couple of imports. 

For a hopefully illustrative example take a look at the build files of this project:
- https://github.com/sbt/sbt-header/blob/master/build.sbt
- https://github.com/sbt/sbt-header/blob/master/project/Build.scala
- https://github.com/sbt/sbt-header/blob/master/project/plugins.sbt

Let me know if you have further questions.

**Comment by pierre-borckmans** [comment]
Thanks, using the new version works flawlessly!
Great little plugin.

Just a small detail. I don't know if it's intended or not, but it removes all the newlines at end of files.

**Comment by pierre-borckmans** [comment]
Another thing, for the moment I have set an empty string for my header.
I intend to include the real one later.
In the meanwhile, every time I compile, I see `Headers created for 62 files:...` with all the modified files even though no files were modified (empty header).
Does it make sense to fix that?

**Comment by hseeberger** [comment]
"I don't know if it's intended or not, but it removes all the newlines at end of files." >> I can't reproduce that. Are you sure that the newlines aren't removed by Scalariform?

Wrt empty header: I assume you are using the `HeaderPattern.cStyleBlockComment` in combination with an empty string. That wouldn't make sense, would it?

**Comment by pierre-borckmans** [comment]
1/ I've been using Scalariform for a very long time and it never removed the newlines. This only happened since I'm using sbt-header. Is it a combination of both then?

2/ I do use `HeaderPattern.cStyleBlockComment` with an empty string, waiting for our project to get its official header. What should I use instead? (for the moment I disabled the auto plugin on compile)

**Comment by hseeberger** [comment]
(1) When I disable sbt-header by removing `enablePlugins(AutomateHeaderPlugin)` from my build Scalariform still removes empty lines. Can you put together a reproducible test case which shows that sat-header is involved?

(2) Well, either don't use the plugin until you know the header or simply use some non-empty header (a simple one-line copyright notice won't hurt too much, will it?); when you change the header later to the proper one sbt-header will update all files with the new one.
