### ISSUE TITLE
please unseal the CommentStyle

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-header#137]
I would like to use this, but I cannot

```scala
  case object SensibleLineComment extends CommentStyle {
    override val commentCreator = new LineCommentCreator("//")
    override val pattern: Regex =
      "(?s)(// Copyright[^\\n]*[\\n]// Licen[cs]e[^\\n]*[\\n])(.*)".r
  }
```

can you please unseal in the next release? Unless you are matching over the ADT there is no point in sealing.

**Comment by britter** [comment]
I don't think we should be doing this. The following configuration should be enough for the use case you described in #139:

```
headerLicense := Some(HeaderLicense.Custom(
  """|Copyright: 2017 https://gitlab.com/fommil/stalactite/graphs
     |License: http://www.gnu.org/licenses/lgpl-3.0.en.html
     |""".stripMargin
))
headerMappings := headerMappings.value + (HeaderFileType.scala -> HeaderCommentStyle.CppStyleLineComment)
```

Of corse we would have to fix #117 in order to create headers without new line between comment and body.

**Comment by fommil** [comment]
I don't think that's enough... my matchers allow for line comments beneath the lines that I care about. I would typically use this when I want to have custom copyright information there.

**Comment by britter** [comment]
I don't understand your use case. Do you have some files which start with `// Copyright: ` but then have something different from `2017 https://gitlab.com/fommil/stalactite/graphs`?

**Comment by fommil** [comment]
yes, exactly. Typically when I've copied some code from elsewhere and am required to include their headers by their terms.

**Comment by britter** [comment]
Looking at `CommentStyle` again, I don't understand why I decided to configure it using inheritance. It would be enough to have:

```scala
sealed trait CommentStyle {
  def pattern: Regex
  def commentCreator: CommentCreator
  // apply methods
}

case class SimpleCommentStyle(
  val pattern: Regex
  val commentCreator: CommentCreator
)

val CStyleBlockComment = SimpleCommentStyle(
  pattern = commentBetween("""/\*+""", "*", """\*/""")
  commentCreator = new CommentBlockCreator("/*", " *", " */")
)

// other implementations
```

This way you could simply instantiate a `SimpleCommentStyle` with the configuration you need. Would that work for you?

**Comment by fommil** [comment]
sounds good!

**Comment by fommil** [comment]
thank you @britter !

**Comment by trobert** [comment]
Is it possible to also unseal `CommentCreator` ? Otherwise it's still impossible to define a custom style.
(As a workaround, one can probably use `IdentityCommentCreator` and include the comments in the license text)

**Comment by hseeberger** [comment]
OMG! This is a can of worms ;-)

@britter, what do you think?
