### ISSUE TITLE
line comments without blank line are ignored?

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-header#139]
in sbt-header 1.x I was using headers that look more or less like this...

```scala
// Copyright: 2017 https://gitlab.com/fommil/stalactite/graphs
// License: http://www.gnu.org/licenses/lgpl-3.0.en.html
package stalactite
```

but the latest `sbt-header` with `CppStyleLineComment` is not detecting this as a header and is then prepending the new header, resulting in 

```scala
// Copyright: 2017 https://gitlab.com/fommil/stalactite/graphs
// License: http://www.gnu.org/licenses/lgpl-3.0.en.html

// Copyright: 2017 https://gitlab.com/fommil/stalactite/graphs
// License: http://www.gnu.org/licenses/lgpl-3.0.en.html
package stalactite
```

I suspect it is the newline to blame... is there a workaround for this? Having support for no trailing newline would be good, if that is what is missing.

**Comment by fommil** [comment]
because of #137 I don't think I can workaround this :cry:

**Comment by britter** [comment]
Is this related to #116?

**Comment by britter** [comment]
Currently sbt-header forces a new line between comment and body. This is probably not the best thing to do, so #117 is an approach to fix this. Unfortunately the contributor lost interest and the PR was never finished.

**Comment by fommil** [comment]
you're quite right, this is a dumb dupe!

**Comment by fommil** [comment]
@britter I'm trying out 4.0.0 with this

```
  val SensibleLineComment = CommentStyle(
    new LineCommentCreator("//"),
    "(?s)(// Copyright[^\\n]*[\\n]// Licen[cs]e[^\\n]*[\\n])(.*)".r
  )

    headerMappings := headerMappings.value +
      (HeaderFileType.scala -> SensibleLineComment) +
      (HeaderFileType.java  -> SensibleLineComment),
```

but it's not detecting my license text that looks like

```
// Copyright: 2017 Sam Halliday
// License: http://www.gnu.org/licenses/gpl.html
```

is there something I'm missing about what the `Regex` is supposed to extract?

**Comment by fommil** [comment]
every time I run `createHeaders` with this comment setup, it adds another newline between the existing header and the code.
