### ISSUE TITLE
where is v4.0.0?

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-header#143]
I see tag v4.0.0 but sbt doesn't find it for 0.13.x... was it only released for sbt 1.0?

**Comment by hseeberger** [comment]
Are people still using 0.x?

**Comment by fommil** [comment]
until the zinc performance regressions are fixed, most projects simply can't upgrade.

**Comment by hseeberger** [comment]
OK, released for 0.13.

**Comment by fommil** [comment]
Thanks! Good news with 1.0 is that we found the cause and it's fixed in the release branch. Hopefully 1.0.4 will be usable.
