### ISSUE TITLE
headerCheck and headerCreate use different source directories

### ISSUE THREAD

**Issue by nrinaudo** [sbt/sbt-header#149]
It seems that in recent versions, `headerCheck` and `headerCreate` do not use the same `unmanagedSources` setting, which results in scenarios where `headerCheck` fails but `headerCreate` cannot fix the problem.

After running a quick investigation, this diff looks suspicious:
* [3.0.x](https://github.com/sbt/sbt-header/blob/23cfdf443ec8fa564cef502768580263b86fad3a/src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala#L117)
* [4.0.0](https://github.com/sbt/sbt-header/blob/fa041e5ca0f5c1ac4ca5c558abfb1384a568b4fc/src/main/scala/de/heikoseeberger/sbtheader/HeaderPlugin.scala#L105)

Is this breaking (at least for my, potentially very specific, use cases) change intended, or is this something that should be fixed?

**Comment by hseeberger** [comment]
That indeed seems to be a bug. PR, please ;-)

**Comment by hseeberger** [comment]
That was my "Code Cleanup" commit #132 😂

**Comment by nrinaudo** [comment]
[PR created](https://github.com/sbt/sbt-header/pull/150). We've all done "code cleanups", I know the feeling :)
