### ISSUE TITLE
Provide an Option to Use the Short SPDX-License-Identifier Syntax

### ISSUE THREAD

**Issue by jamesward** [sbt/sbt-header#155]
The new cool way to specify the license is with a machine-readable `SPDX-License-Identifier` line:
https://spdx.org/sites/cpstandard/files/pages/files/using_spdx_license_list_short_identifiers.pdf

Like:
```
Copyright (c) 2018, Foo Bar
SPDX-License-Identifier: BSD-3-Clause
```

**Comment by britter** [comment]
Can you give an example of how you'd like to use this with sbt-header? Currently we detect the license from the `licenses` setting.

**Comment by jamesward** [comment]
This is just a different style for indicating the license in the header.  You can see an example here:
https://github.com/salesforce/dr-cla/blob/master/app/controllers/Application.scala

But to do this I had to manually specify the template:
https://github.com/salesforce/dr-cla/blob/master/build.sbt#L53-L61

I'd be nice if there was a way to easily use this syntax with sbt-header.

**Comment by hseeberger** [comment]
Hey @jamesward, that would be a nice contribution ;-)

**Comment by britter** [comment]
Okay, so you would like to have a boolean switch to turn on SPDX-style headers?

**Comment by jamesward** [comment]
Yeah, I think a custom setting like `licenseHeaderStyle` would be sufficient.

**Comment by jhoncamargo** [comment]
@hseeberger @britter I'd like to work on this. How can I start?
