### ISSUE TITLE
Double newline after header

### ISSUE THREAD

**Issue by raboof** [sbt/sbt-header#156]
Currently https://github.com/sbt/sbt-header/blob/master/src/main/scala/de/heikoseeberger/sbtheader/CommentStyle.scala#L31 forces an empty line between the header and the actual file. For Java/Scala files like:

```
/*
 * Some License
 */

package foo

import bar
```

that doesn't necessarily make sense. It might make sense to move one of the newlines to the `CommentCreator` instead?

**Comment by britter** [comment]
This has been suggested before, see #117. It was never completed...

**Comment by raboof** [comment]
OK, to summarize that thread it seems you'd still be interested in this feature, if we can pull it off without introducing too much additional complexity?

**Comment by hseeberger** [comment]
Yeah, if you can keep it really simple. It‘s just an empty line after all ...

**Comment by dwijnand** [comment]
I've opened https://github.com/sbt/sbt-header/pull/164 to see if I can help fix this.
