### ISSUE TITLE
Publish to maven central instead of bintray

### ISSUE THREAD

**Issue by Isammoc** [sbt/sbt-header#233]
Thank you for this plugin! We love it! And we don't want to lose it when JFrog will sunset bintray/jcenter.

Can you publish to maven central (or any other public repository that won't be sunset soon)? :pray: 

References:
sbt/sbt#6294
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

As this repo is part of "sbt" GitHub organization: cc @eed3si9n

**Comment by hseeberger** [comment]
Thanks @Isammoc for bringing this up.

@eed3si9n do we have a new place for sbt plugins?

**Comment by eed3si9n** [comment]
We're planning on migrating existing versions on Bintray to somewhere read-only.

New versions should be published to Maven Central.

**Comment by Philippus** [comment]
5.6.5 is released on maven now.

**Comment by mkurz** [comment]
Can be closed I guess.
