### ISSUE TITLE
The plugin should not be targeting JDK7

### ISSUE THREAD

**Issue by pdalpra** [sbt/sbt-header#27]
As SBT itself is targeting JDK6, I think that sbt-header should not  set `-target:jvm-1.7` to target JDK7.

**Comment by hseeberger** [comment]
Actually I think sbt-header should target Java 8, because both Java 6 and 7 are EOL.

**Comment by pdalpra** [comment]
Indeed, Java 6 and 7 are EOL, but since Scala 2.11 default target is still 1.6 and SBT itself requires JDK6 (to the point you cannot fully build SBT if you're not explicitly using a JDK6) and is based on Scala 2.10, I thought I could be good to keep versions aligned until both Scala and SBT move to an higher default target :)

**Comment by hseeberger** [comment]
I understand your reasoning, but I prefer to not look forward in this case ;-)
