### ISSUE TITLE
ability to ignore some files

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-header#30]
We have some files that have been copied from another project and have additional copyright / license information that must be displayed. Is it possible to ignore such files?

I'm thinking of a workaround whereby those files simply have two header sections.

**Comment by sirthias** [comment]
+1
Same here.

I think I'd prefer some way of marking a particular header as "untouchable", e.g. via another regex.
And a task showing me all the files with "KEEP" headers would be the cherry on the cake... :)

**Comment by hseeberger** [comment]
Ouch. This little innocent project is getting too much attention. I don't have any spare cycles to work on this or similar issues these days. But hey, of course this is open source and you can help yourself and create PRs.

**Comment by sirthias** [comment]
There is no such thing as "too much attention" in OSS... :)

**Comment by hseeberger** [comment]
... in theory ;-)

**Comment by fommil** [comment]
heh, funny I was thinking about this today.

I'll be giving a talk about copyright / licensing at ScalaSphere. It's only 15 minutes, so not enough time to fall asleep at the back.
