### ISSUE TITLE
build on JDK6

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-header#31]
inclusion of this plugin leads to:

```
java.lang.UnsupportedClassVersionError: de/heikoseeberger/sbtheader/AutomateHeaderPlugin$ : Unsupported major.minor version 51.0
```

it would be good to support JDK6 as it is still the official JDK for Scala and is therefore used in many CIs. (I actually use it locally for my OSS projects to avoid discovering the pain only when merging)

**Comment by hseeberger** [comment]
Sorry, but I'm not willing to support Java 6. I'd even not support Java 7, but sbt is still on Scala 2.10 and there's no Java 8 for it.

**Comment by fommil** [comment]
that sucks, it means we can't use this in ENSIME, or actually any project that supports android. Are you using the java 7 APIs?

**Comment by hseeberger** [comment]
Why is ENSIME on Java 6?
And yes, this project makes use of Java 7 API. Only a little bit, though.

Closing this issue was premature, I have opened it again in case you want to give it a try.

**Comment by fommil** [comment]
I might! Since I'm giving a talk about this sort of thing, I might touch up this plugin so that I can recommend it. In fact, if you want to transfer it to me I'd be happy to maintain it.

**Comment by hseeberger** [comment]
Aye, now you're an admin. Thanks for helping!

**Comment by fommil** [comment]
oh darn, what have I done :smile:

actually this might be a good one-day task for somebody at the hack day on Saturday, if not my flight to Poland next week.

**Comment by britter** [comment]
@fommil I don't see us ever fixing this... Okay to close this?

**Comment by fommil** [comment]
Yeah. Ensime is now java 8
