### ISSUE TITLE
integration with git history

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-header#35]
It would be great to have an option to generate the copyright years and names based on the github history. That section in the template notice could then become a placeholder, to be auto-generated.

This would be prone to errors, so it is likely that overrides (not captured by the history) and blacklists (dupes and bots) would need to be provided. This could perhaps be provided on a per file basis using a syntax in the comments much like emacs' local variables.

**Comment by FelAl** [comment]
I take it.

**Comment by fommil** [comment]
@felal did you make any progress? :-)

**Comment by FelAl** [comment]
Not very much, but I'm going to fix it )

**Comment by dwijnand** [comment]
just for reference here's some code attempting to fix this problem:

* https://github.com/scala/scala/pull/5201/commits/71b38e6427be39add62bd8b04e88940b8da78450
* 	https://github.com/scala/scala/pull/5145/commits/8b8f93a5edba6fcb8271dca98a2f7ecf93c3ce8c
