### ISSUE TITLE
integration tests automation is broken

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-header#37]
Although the `automateFor` idea is nice, it unfortunately does not work because `settingsFor` will not be set for the `IntegrationTest` config. Nice try!

**Comment by hseeberger** [comment]
It's not broken! You have to call `settingsFor` and `automateFor` for all configurations.
See https://github.com/hseeberger/reactive-flows/blob/master/build.sbt#L57.

**Comment by fommil** [comment]
I think there might be a way to do this automatically, but it'll probably involve doing some trickery that I'm certain Josh and Eugene will yell at me for (it's possible to go "off graph" and call tasks / settings dynamically for any project and get its ivy configs...)

**Comment by fommil** [comment]
maybe automateFor should also imply settingsFor ?

**Comment by onnoll** [comment]
Hi there,
any update for this issue? any work around?
Thanks

**Comment by fommil** [comment]
(waits for @onnoll to read the comments...)
