### ISSUE TITLE
Support for file exclusion

### ISSUE THREAD

**Issue by joprice** [sbt/sbt-header#46]
Is there a way to exclude particular files from getting headers? The use-case is when a project needs to include a file taken from another project, which already has a header.

**Comment by polymorphic** [comment]
+1 I'm also interested in this feature which comes in handy when integrating source files covered by different licenses.

**Comment by britter** [comment]
This is a duplicate of #30

**Comment by joprice** [comment]
Duplicates mean there's lots of interest, especially among the hastier of us. 😄
