### ISSUE TITLE
UnmappableCharacterException? 

### ISSUE THREAD

**Issue by danyaljj** [sbt/sbt-header#58]
We are using [sbt-header](https://github.com/IllinoisCogComp/saul/blob/master/project/plugins.sbt#L7-L8). 
Upon running the code in Windows, we get `UnmappableCharacterException` (while it works fine in OSX). Any ideas? 
More here: https://github.com/IllinoisCogComp/saul/issues/447

**Comment by britter** [comment]
@danyaljj I suspect it has something to do with the definition of `headerMsg` in your build file. Can you try changing the definition of the `headers` key to:

```scala
  headers := Map(
    "scala" -> Apache2_0("2017", "Your Company"),
    "java" -> Apache2_0("2017", "Your Company")
 )
```

And see whether this works on Windows?

**Comment by danyaljj** [comment]
Actually we recently resolved it. @bhargav could you remind me what was the issue?

**Comment by bhargav** [comment]
On Windows, we had to explicitly set the JAVA file encoding parameter to "UTF-8". Setting `-Dfile.encoding=UTF8" in JAVA_TOOL_OPTIONS env variable fixed the issue for us.

**Comment by richdougherty** [comment]
This issue occurs during the Play Framework build. Issue created here: https://github.com/playframework/playframework/issues/8150
