### ISSUE TITLE
use of scope ThisBuild doesn't seem to work

### ISSUE THREAD

**Issue by brendon-** [sbt/sbt-header#59]
in a multiModule project you can use things like

scalaVersion in ThisBuild := [some-version]

which will apply to all submodules in the project

however, `headers in ThisBuild:=` does not seem to work.

**Comment by hseeberger** [comment]
someSetting in ThisBuild only lets you override such settings which are not queried more specifically and already defined more specifically. For headers there is already a project level setting (for good purpose) and that will be used. 

You can define common project settings once and assign it to multiple projects.
