### ISSUE TITLE
Support for Play Twirl template files

### ISSUE THREAD

**Issue by johno1985** [sbt/sbt-header#60]
It would be nice to support commenting of Play Twirl template files

https://www.playframework.com/documentation/2.5.x/ScalaTemplates#Comments

**Comment by britter** [comment]
@johno1985 I'm working on this, see #64. Which comment style do you prefer for license headers in twirl templates? Currently I've implemented block comments of the form:

```
@****************
 * License text *
 ****************@
```

An alternative would be to create them like this:

```
@*
 * License text
 *@
```

We could also make it configurable...

**Comment by johno1985** [comment]
Hi @britter, I think we would prefer the latter. But it may be a good idea to make this configurable for other consumers.

**Comment by britter** [comment]
@johno1985 please have a look at #72

**Comment by johno1985** [comment]
Thanks @britter
