### ISSUE TITLE
Releasing 1.6.1

### ISSUE THREAD

**Issue by dotta** [sbt/sbt-header#62]
I'd love to use https://github.com/sbt/sbt-header/issues/30, but the latest release (1.6.0) doesn't seem to include the functionality. Would it be possible to cut a new release? \cc @fommil (as you contributed the feature, maybe you have also released it somewhere? :))

**Comment by fommil** [comment]
I think heikko did that.

Btw you don't need to wait, you can put plugins into your project dir

**Comment by dotta** [comment]
I've ended up adding the following in my `project/plugins.sbt`

```
lazy val root = project.in(file(".")).dependsOn(sbtHeaderPlugin)
lazy val sbtHeaderPlugin = uri("https://github.com/sbt/sbt-header.git")
```

Though, it'd really be better if a release could be cut :)

**Comment by hseeberger** [comment]
Release 1.7.0 has arrived ;-)

**Comment by fommil** [comment]
fyi @britter implemented it :smile:

**Comment by dotta** [comment]
Whohooo! Thanks, Heiko!

@fommil Thanks for the note, and please forgive me @britter for not giving credit to the right person.

**Comment by britter** [comment]
@dotta happy you like it!
